language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nehsus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nehsus/react-test npm run test

after_success:
  - docker build -t sushen/multi-client ./client
  - docker build -t sushen/multi-nginx ./nginx
  - docker build -t sushen/multi-worker ./worker
  - docker build -t sushen/multi-server ./server

  #Login to Travis CI
  - echo "$DOCKER_KEY" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sushen/multi-client
  - docker push sushen/multi-nginx
  - docker push sushen/multi-worker
  - docker push sushen/multi-server